addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.9.34")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"       % "2.0.0-M4")
addSbtPlugin("dev.guardrail"  % "sbt-guardrail"       % "0.74.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.9")
